spring.application.name=capacity_ms

spring.r2dbc.url=r2dbc:mysql://localhost:3306/capacity
spring.r2dbc.username=root
spring.r2dbc.password=admin

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

adapters.technology-ms.url=http://localhost:8080

server.port=8081